<?php

namespace AppBundle\Repository;

/**
 * FavorecidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorecidoRepository extends \Doctrine\ORM\EntityRepository
{
}
