<?php

namespace AppBundle\Repository;

/**
 * gastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gastoRepository extends \Doctrine\ORM\EntityRepository
{
}
