<?php

namespace AppBundle\Repository;

/**
 * orgaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orgaoRepository extends \Doctrine\ORM\EntityRepository
{
}
