<?php

namespace AppBundle\Repository;

/**
 * pessoaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pessoaRepository extends \Doctrine\ORM\EntityRepository
{
}
