<?php

namespace AppBundle\Repository;

/**
 * PortadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortadorRepository extends \Doctrine\ORM\EntityRepository
{
}
