<?php

namespace AppBundle\Repository;

/**
 * unidadeGestoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unidadeGestoraRepository extends \Doctrine\ORM\EntityRepository
{
}
